import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/features/Navbar";
import AuthSession from "./utils/AuthSession";
import { Session, getServerSession } from "next-auth";
import { handler } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = (await getServerSession(handler)) as Session;
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthSession session={session}>
                    <Navbar />
                    {children}
                </AuthSession>
            </body>
        </html>
    );
}
